// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Turso URL (with auth token embedded) when available, else local SQLite file
    url: process.env["TURSO_URL"]
      ? `${process.env["TURSO_URL"]}?authToken=${process.env["TURSO_AUTH_TOKEN"]}`
      : process.env["DATABASE_URL"],
  },
});
